// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/tool/github"
	_ "github.com/lewtec/lewkit/x/tool/mise"
	_ "github.com/lewtec/lewkit/x/tool/registry"
	_ "github.com/lewtec/lewkit/x/tool/registry/applications"
)
