// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/filedialog/cocoa"
	_ "github.com/lewtec/lewkit/x/driver/filedialog/gtk"
	_ "github.com/lewtec/lewkit/x/driver/filedialog/qt"
	_ "github.com/lewtec/lewkit/x/driver/filedialog/win32"
)
