// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/webview/webkitgtk"
	_ "github.com/lewtec/lewkit/x/driver/webview/webview2"
	_ "github.com/lewtec/lewkit/x/driver/webview/wkwebview"
)
