// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/audio_play/coreaudio"
	_ "github.com/lewtec/lewkit/x/driver/audio_play/mem"
	_ "github.com/lewtec/lewkit/x/driver/audio_play/pulse"
	_ "github.com/lewtec/lewkit/x/driver/audio_play/winmm"
)
