// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

type Track struct {
	ID         int64
	Path       string
	Title      string
	Artist     string
	Album      string
	Cover      string
	DurationMs int64
}
