// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracks.sql

package sqlite

import (
	"context"
)

const listAlbums = `-- name: ListAlbums :many
SELECT album, MIN(artist) AS artist, MAX(cover) AS cover, COUNT(*) AS tracks
FROM tracks
WHERE ? = '' OR title LIKE ? OR artist LIKE ? OR album LIKE ?
GROUP BY album
ORDER BY album
`

type ListAlbumsParams struct {
	Column1 interface{}
	Title   string
	Artist  string
	Album   string
}

type ListAlbumsRow struct {
	Album  string
	Artist interface{}
	Cover  interface{}
	Tracks int64
}

func (q *Queries) ListAlbums(ctx context.Context, arg ListAlbumsParams) ([]ListAlbumsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbums,
		arg.Column1,
		arg.Title,
		arg.Artist,
		arg.Album,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsRow
	for rows.Next() {
		var i ListAlbumsRow
		if err := rows.Scan(
			&i.Album,
			&i.Artist,
			&i.Cover,
			&i.Tracks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracks = `-- name: ListTracks :many
SELECT id, path, title, artist, album, cover, duration_ms
FROM tracks
WHERE (? = '' OR album = ?)
  AND (? = '' OR title LIKE ? OR artist LIKE ?)
ORDER BY title
`

type ListTracksParams struct {
	Column1 interface{}
	Album   string
	Column3 interface{}
	Title   string
	Artist  string
}

func (q *Queries) ListTracks(ctx context.Context, arg ListTracksParams) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, listTracks,
		arg.Column1,
		arg.Album,
		arg.Column3,
		arg.Title,
		arg.Artist,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Cover,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrack = `-- name: UpsertTrack :exec
INSERT INTO tracks (path, title, artist, album, cover, duration_ms)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(path) DO UPDATE SET
    title = excluded.title,
    artist = excluded.artist,
    album = excluded.album,
    cover = excluded.cover,
    duration_ms = excluded.duration_ms
`

type UpsertTrackParams struct {
	Path       string
	Title      string
	Artist     string
	Album      string
	Cover      string
	DurationMs int64
}

func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrack,
		arg.Path,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.Cover,
		arg.DurationMs,
	)
	return err
}
