// Package prelude registers every driver implementation via blank imports.
// A directory that contains a descendant root.go has its own prelude, for
// example x/driver/webview/prelude. Regenerated by `go generate` at the module root.
package prelude
