// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/audio_play/coreaudio"
	_ "github.com/lewtec/lewkit/x/driver/audio_play/mem"
	_ "github.com/lewtec/lewkit/x/driver/audio_play/pulse"
	_ "github.com/lewtec/lewkit/x/driver/audio_play/winmm"
	_ "github.com/lewtec/lewkit/x/driver/fetchurl/native"
	_ "github.com/lewtec/lewkit/x/driver/httpclient/native"
	_ "github.com/lewtec/lewkit/x/driver/ndeval"
	_ "github.com/lewtec/lewkit/x/driver/tray/cocoa"
	_ "github.com/lewtec/lewkit/x/driver/tray/dbus"
	_ "github.com/lewtec/lewkit/x/driver/tray/win32"
	_ "github.com/lewtec/lewkit/x/driver/vulkan"
	_ "github.com/lewtec/lewkit/x/driver/vulkanwindow"
	_ "github.com/lewtec/lewkit/x/driver/webview/webkitgtk"
	_ "github.com/lewtec/lewkit/x/driver/webview/webview2"
	_ "github.com/lewtec/lewkit/x/driver/webview/wkwebview"
	_ "github.com/lewtec/lewkit/x/driver/window/cocoa"
	_ "github.com/lewtec/lewkit/x/driver/window/mem"
	_ "github.com/lewtec/lewkit/x/driver/window/win32"
	_ "github.com/lewtec/lewkit/x/driver/window/x11"
)
