// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/audio_play/prelude"
	_ "github.com/lewtec/lewkit/x/driver/daynight/prelude"
	_ "github.com/lewtec/lewkit/x/driver/fetchurl/prelude"
	_ "github.com/lewtec/lewkit/x/driver/filedialog/prelude"
	_ "github.com/lewtec/lewkit/x/driver/httpclient/prelude"
	_ "github.com/lewtec/lewkit/x/driver/ndeval"
	_ "github.com/lewtec/lewkit/x/driver/tray/prelude"
	_ "github.com/lewtec/lewkit/x/driver/vulkan"
	_ "github.com/lewtec/lewkit/x/driver/vulkanwindow"
	_ "github.com/lewtec/lewkit/x/driver/webview/prelude"
	_ "github.com/lewtec/lewkit/x/driver/window/prelude"
)
