// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/audio_play/prelude"
	_ "github.com/lewtec/lewkit/x/driver/battery/prelude"
	_ "github.com/lewtec/lewkit/x/driver/brightness/prelude"
	_ "github.com/lewtec/lewkit/x/driver/camera/prelude"
	_ "github.com/lewtec/lewkit/x/driver/clipboard/prelude"
	_ "github.com/lewtec/lewkit/x/driver/daynight/prelude"
	_ "github.com/lewtec/lewkit/x/driver/dirs/prelude"
	_ "github.com/lewtec/lewkit/x/driver/fetchurl/prelude"
	_ "github.com/lewtec/lewkit/x/driver/filedialog/prelude"
	_ "github.com/lewtec/lewkit/x/driver/httpclient/prelude"
	_ "github.com/lewtec/lewkit/x/driver/launcher/prelude"
	_ "github.com/lewtec/lewkit/x/driver/media/prelude"
	_ "github.com/lewtec/lewkit/x/driver/ndeval"
	_ "github.com/lewtec/lewkit/x/driver/notification/prelude"
	_ "github.com/lewtec/lewkit/x/driver/opener/prelude"
	_ "github.com/lewtec/lewkit/x/driver/power/prelude"
	_ "github.com/lewtec/lewkit/x/driver/screen/prelude"
	_ "github.com/lewtec/lewkit/x/driver/screenshot/prelude"
	_ "github.com/lewtec/lewkit/x/driver/share/prelude"
	_ "github.com/lewtec/lewkit/x/driver/terminal/prelude"
	_ "github.com/lewtec/lewkit/x/driver/tray/prelude"
	_ "github.com/lewtec/lewkit/x/driver/volume/prelude"
	_ "github.com/lewtec/lewkit/x/driver/vulkan"
	_ "github.com/lewtec/lewkit/x/driver/vulkanwindow"
	_ "github.com/lewtec/lewkit/x/driver/wallpaper/prelude"
	_ "github.com/lewtec/lewkit/x/driver/webview/prelude"
	_ "github.com/lewtec/lewkit/x/driver/window/prelude"
	_ "github.com/lewtec/lewkit/x/driver/wm/prelude"
)
