package shader

import (
	"context"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"testing"

	"github.com/lewtec/lewkit/x/generate"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestIdent(t *testing.T) {
	assert.Equal(t, "exampleCompute", ident("example.compute.glsl"))
	assert.Equal(t, "shaderFillVertex", ident("shader/fill.vertex.glsl"))
	assert.Equal(t, "shaderFillFragment", ident("shader/fill.fragment.glsl"))
	assert.Equal(t, "shaderInkVertex", ident("shader/ink.vertex.glsl"))
	assert.Equal(t, "myShaderCompute", ident("my-shader.compute.glsl"))
	assert.Equal(t, "shader1Compute", ident("1.compute.glsl"))
	assert.Equal(t, "shader", ident("notes.glsl"))
	assert.Equal(t, "shader", ident("fill.vert"))
}

func TestRunEmptyDir(t *testing.T) {
	err := Run(t.Context(), "")
	assert.ErrorIs(t, err, generate.ErrDirRequired)
}

func TestRunCancel(t *testing.T) {
	ctx, cancel := context.WithCancel(t.Context())
	cancel()
	err := Run(ctx, t.TempDir())
	assert.ErrorIs(t, err, context.Canceled)
}

func TestRunNoPackage(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "orphan.compute.glsl"), []byte("#version 450\nvoid main() {}\n"), 0o644))
	err := Run(t.Context(), dir)
	assert.ErrorIs(t, err, errNoPackage)
	_, statErr := os.Stat(filepath.Join(dir, generatedName))
	assert.ErrorIs(t, statErr, os.ErrNotExist)
}

func TestRunWritesRegistry(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, map[string]string{
		"app/root.go": "package app\n",
		"app/demo.compute.glsl": `#version 450
layout(local_size_x = 1) in;
void main() {}
`,
		"app/shader/fill.vertex.glsl": `#version 450
void main() { gl_Position = vec4(0.0); }
`,
		"app/shader/fill.fragment.glsl": `#version 450
layout(location = 0) out vec4 outColor;
void main() { outColor = vec4(1.0); }
`,
		"app/notes.glsl":                     "#version 450\nvoid main() {}\n",
		"app/legacy.vert":                    "#version 450\nvoid main() {}\n",
		"app/node_modules/skip.compute.glsl": "#version 450\nvoid main() {}\n",
		"app/other/leaf.go":                  "package leaf\n",
		"app/other/leaf.compute.glsl": `#version 450
layout(local_size_x = 1) in;
void main() {}
`,
	})
	require.NoError(t, Run(t.Context(), dir))

	app := readFile(t, filepath.Join(dir, "app", generatedName))
	assert.Contains(t, app, "Code generated by lewkit generate shader. DO NOT EDIT.")
	assert.Contains(t, app, "package app")
	assert.Contains(t, app, "glsl.MustRegisterHash(glsl.StageCompute, [32]byte{")
	assert.Contains(t, app, "glsl.MustRegisterHash(glsl.StageVertex, [32]byte{")
	assert.Contains(t, app, "glsl.MustRegisterHash(glsl.StageFragment, [32]byte{")
	assert.Contains(t, app, "[]byte{")
	assert.Contains(t, app, "// demo.compute.glsl")
	assert.Contains(t, app, "0x03, 0x02, 0x23, 0x07,")
	assert.NotContains(t, app, "\nvar ")
	assert.NotContains(t, app, "node_modules")
	assert.NotContains(t, app, "leafCompute")
	assert.NotContains(t, app, "notes.glsl")
	assert.NotContains(t, app, "legacy.vert")
	_, err := parser.ParseFile(token.NewFileSet(), "spirv_gen.go", app, parser.SkipObjectResolution)
	require.NoError(t, err)

	leaf := readFile(t, filepath.Join(dir, "app", "other", generatedName))
	assert.Contains(t, leaf, "package leaf")
	assert.Contains(t, leaf, "glsl.MustRegisterHash(glsl.StageCompute, [32]byte{")
	assert.Contains(t, leaf, "[]byte{")
	assert.Contains(t, leaf, "// leaf.compute.glsl")
	assert.NotContains(t, leaf, "\nvar ")
	_, err = parser.ParseFile(token.NewFileSet(), "spirv_gen.go", leaf, parser.SkipObjectResolution)
	require.NoError(t, err)

	again := readFile(t, filepath.Join(dir, "app", generatedName))
	require.NoError(t, Run(t.Context(), dir))
	assert.Equal(t, again, readFile(t, filepath.Join(dir, "app", generatedName)))
}

func writeTree(t *testing.T, root string, files map[string]string) {
	t.Helper()
	for rel, body := range files {
		name := filepath.Join(root, filepath.FromSlash(rel))
		require.NoError(t, os.MkdirAll(filepath.Dir(name), 0o755))
		require.NoError(t, os.WriteFile(name, []byte(body), 0o644))
	}
}

func readFile(t *testing.T, name string) string {
	t.Helper()
	body, err := os.ReadFile(name)
	require.NoError(t, err)
	return string(body)
}

func TestUniqueIdent(t *testing.T) {
	used := map[string]int{}
	assert.Equal(t, "fillVert", uniqueIdent("fillVert", used))
	assert.Equal(t, "fillVert2", uniqueIdent("fillVert", used))
}
