package shader

import (
	"bytes"
	"context"
	"fmt"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"unicode"

	"github.com/dave/jennifer/jen"
	"github.com/lewtec/lewkit/x/ffi/wasm/glsl"
)

const generatedBy = "Code generated by lewkit generate shader. DO NOT EDIT."

const glslPath = "github.com/lewtec/lewkit/x/ffi/wasm/glsl"

const hexWidth = 12

func writePackage(ctx context.Context, dir string, files []shaderFile) error {
	pkg, err := goPackage(dir)
	if err != nil {
		return err
	}
	if !token.IsIdentifier(pkg) {
		return fmt.Errorf("%w: %s", errNoPackage, pkg)
	}
	type compiled struct {
		rel   string
		stage glsl.Stage
		hash  [32]byte
		spirv []byte
	}
	out := make([]compiled, 0, len(files))
	for _, file := range files {
		if err := ctx.Err(); err != nil {
			return err
		}
		src, err := os.ReadFile(file.abs)
		if err != nil {
			return err
		}
		spirv, err := glsl.CompileGlslang(ctx, file.stage, src)
		if err != nil {
			return fmt.Errorf("%s: %w", file.rel, err)
		}
		out = append(out, compiled{
			rel:   file.rel,
			stage: file.stage,
			hash:  glsl.Hash(file.stage, src),
			spirv: spirv,
		})
	}
	f := jen.NewFile(pkg)
	f.HeaderComment(generatedBy)
	f.ImportName(glslPath, "glsl")
	f.Func().Id("init").Params().BlockFunc(func(g *jen.Group) {
		for _, file := range out {
			g.Comment(file.rel)
			g.Qual(glslPath, "MustRegisterHash").Call(
				stageCode(file.stage),
				jen.Index(jen.Lit(32)).Byte().Add(hexValues(file.hash[:])),
				jen.Index().Byte().Add(hexValues(file.spirv)),
			)
		}
	})
	var body bytes.Buffer
	if err := f.Render(&body); err != nil {
		return fmt.Errorf("%s: %w", generatedName, err)
	}
	tmp := filepath.Join(dir, generatedName+".tmp")
	if err := os.WriteFile(tmp, body.Bytes(), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, filepath.Join(dir, generatedName))
}

func stageCode(stage glsl.Stage) jen.Code {
	switch stage {
	case glsl.StageVertex:
		return jen.Qual(glslPath, "StageVertex")
	case glsl.StageFragment:
		return jen.Qual(glslPath, "StageFragment")
	default:
		return jen.Qual(glslPath, "StageCompute")
	}
}

func hexValues(raw []byte) jen.Code {
	return jen.CustomFunc(jen.Options{
		Open:      "{",
		Close:     "}",
		Separator: ",",
		Multi:     true,
	}, func(g *jen.Group) {
		for start := 0; start < len(raw); start += hexWidth {
			end := start + hexWidth
			if end > len(raw) {
				end = len(raw)
			}
			g.Add(hexLine(raw[start:end]))
		}
	})
}

func hexLine(raw []byte) jen.Code {
	parts := make([]jen.Code, len(raw))
	for i, b := range raw {
		parts[i] = jen.Op(fmt.Sprintf("0x%02x", b))
	}
	return jen.List(parts...)
}

func stageToken(stage glsl.Stage) string {
	switch stage {
	case glsl.StageVertex:
		return "vertex"
	case glsl.StageFragment:
		return "fragment"
	default:
		return "compute"
	}
}

func ident(rel string) string {
	stem, stage, ok := splitShader(rel)
	if !ok {
		return "shader"
	}
	var parts []string
	for _, part := range strings.Split(stem, "/") {
		parts = append(parts, words(part)...)
	}
	parts = append(parts, stageToken(stage))
	parts = slices.DeleteFunc(parts, func(part string) bool { return part == "" })
	if len(parts) == 0 {
		return "shader"
	}
	var b strings.Builder
	for i, part := range parts {
		lower := strings.ToLower(part)
		if i == 0 {
			b.WriteString(lower)
			continue
		}
		b.WriteString(strings.ToUpper(lower[:1]))
		if len(lower) > 1 {
			b.WriteString(lower[1:])
		}
	}
	name := b.String()
	if name == "" {
		name = "shader"
	}
	if r := rune(name[0]); r >= '0' && r <= '9' {
		name = "shader" + strings.ToUpper(name[:1]) + name[1:]
	}
	if !token.IsIdentifier(name) || token.IsKeyword(name) {
		name = "shader" + strings.ToUpper(name[:1]) + name[1:]
	}
	return name
}

func words(part string) []string {
	var cur strings.Builder
	var out []string
	flush := func() {
		if cur.Len() == 0 {
			return
		}
		out = append(out, cur.String())
		cur.Reset()
	}
	for _, r := range part {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			cur.WriteRune(r)
			continue
		}
		flush()
	}
	flush()
	return out
}

func uniqueIdent(name string, used map[string]int) string {
	n := used[name]
	used[name] = n + 1
	if n == 0 {
		return name
	}
	return fmt.Sprintf("%s%d", name, n+1)
}
