package shader

import (
	"context"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"unicode"

	"github.com/lewtec/lewkit/x/ffi/wasm/glsl"
)

func writePackage(ctx context.Context, dir string, files []shaderFile) error {
	pkg, err := goPackage(dir)
	if err != nil {
		return err
	}
	if !token.IsIdentifier(pkg) {
		return fmt.Errorf("%w: %s", errNoPackage, pkg)
	}
	type compiled struct {
		rel   string
		ident string
		stage glsl.Stage
		hash  [32]byte
		spirv []byte
	}
	out := make([]compiled, 0, len(files))
	used := map[string]int{}
	for _, file := range files {
		if err := ctx.Err(); err != nil {
			return err
		}
		src, err := os.ReadFile(file.abs)
		if err != nil {
			return err
		}
		spirv, err := glsl.CompileGlslang(ctx, file.stage, src)
		if err != nil {
			return fmt.Errorf("%s: %w", file.rel, err)
		}
		name := uniqueIdent(ident(file.rel), used)
		out = append(out, compiled{
			rel:   file.rel,
			ident: name,
			stage: file.stage,
			hash:  glsl.Hash(file.stage, src),
			spirv: spirv,
		})
	}
	var body strings.Builder
	body.WriteString("// Code generated by lewkit generate shader. DO NOT EDIT.\n\n")
	fmt.Fprintf(&body, "package %s\n\n", pkg)
	body.WriteString("import \"github.com/lewtec/lewkit/x/ffi/wasm/glsl\"\n\n")
	body.WriteString("func init() {\n")
	for _, file := range out {
		fmt.Fprintf(&body, "\tglsl.MustRegisterHash(%s, %sHash, %sSPIRV)\n", stageExpr(file.stage), file.ident, file.ident)
	}
	body.WriteString("}\n")
	for _, file := range out {
		fmt.Fprintf(&body, "\n// %s\n", file.rel)
		writeBytes(&body, file.ident+"Hash", "[32]byte", file.hash[:])
		body.WriteByte('\n')
		writeBytes(&body, file.ident+"SPIRV", "[]byte", file.spirv)
		body.WriteByte('\n')
	}
	formatted, err := format.Source([]byte(body.String()))
	if err != nil {
		return fmt.Errorf("spirv_gen.go: %w", err)
	}
	tmp := filepath.Join(dir, generatedName+".tmp")
	if err := os.WriteFile(tmp, formatted, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, filepath.Join(dir, generatedName))
}

func stageExpr(stage glsl.Stage) string {
	switch stage {
	case glsl.StageVertex:
		return "glsl.StageVertex"
	case glsl.StageFragment:
		return "glsl.StageFragment"
	default:
		return "glsl.StageCompute"
	}
}

func ident(rel string) string {
	ext := filepath.Ext(rel)
	stem := strings.TrimSuffix(rel, ext)
	var parts []string
	for _, part := range strings.Split(stem, "/") {
		parts = append(parts, words(part)...)
	}
	switch ext {
	case ".vert":
		parts = append(parts, "vert")
	case ".frag":
		parts = append(parts, "frag")
	case ".comp":
		parts = append(parts, "comp")
	}
	parts = slices.DeleteFunc(parts, func(part string) bool { return part == "" })
	if len(parts) == 0 {
		return "shader"
	}
	var b strings.Builder
	for i, part := range parts {
		lower := strings.ToLower(part)
		if i == 0 {
			b.WriteString(lower)
			continue
		}
		b.WriteString(strings.ToUpper(lower[:1]))
		if len(lower) > 1 {
			b.WriteString(lower[1:])
		}
	}
	name := b.String()
	if name == "" {
		name = "shader"
	}
	if r := rune(name[0]); r >= '0' && r <= '9' {
		name = "shader" + strings.ToUpper(name[:1]) + name[1:]
	}
	if !token.IsIdentifier(name) || token.IsKeyword(name) {
		name = "shader" + strings.ToUpper(name[:1]) + name[1:]
	}
	return name
}

func words(part string) []string {
	var cur strings.Builder
	var out []string
	flush := func() {
		if cur.Len() == 0 {
			return
		}
		out = append(out, cur.String())
		cur.Reset()
	}
	for _, r := range part {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			cur.WriteRune(r)
			continue
		}
		flush()
	}
	flush()
	return out
}

func uniqueIdent(name string, used map[string]int) string {
	n := used[name]
	used[name] = n + 1
	if n == 0 {
		return name
	}
	return fmt.Sprintf("%s%d", name, n+1)
}

func writeBytes(b *strings.Builder, name, typ string, raw []byte) {
	fmt.Fprintf(b, "var %s = %s{", name, typ)
	if len(raw) == 0 {
		b.WriteString("}\n")
		return
	}
	b.WriteByte('\n')
	for i, v := range raw {
		if i%12 == 0 {
			b.WriteByte('\t')
		}
		fmt.Fprintf(b, "0x%02x,", v)
		if i%12 == 11 || i == len(raw)-1 {
			b.WriteByte('\n')
		} else {
			b.WriteByte(' ')
		}
	}
	b.WriteString("}\n")
}
