// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/brightness/android"
	_ "github.com/lewtec/lewkit/x/driver/brightness/brightnessctl"
)
