// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/launcher/rofi"
	_ "github.com/lewtec/lewkit/x/driver/launcher/terminal"
	_ "github.com/lewtec/lewkit/x/driver/launcher/wofi"
	_ "github.com/lewtec/lewkit/x/driver/launcher/zenity"
)
