// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/opener/macopen"
	_ "github.com/lewtec/lewkit/x/driver/opener/winstart"
	_ "github.com/lewtec/lewkit/x/driver/opener/xdg"
)
