// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/battery/android"
	_ "github.com/lewtec/lewkit/x/driver/battery/darwin"
	_ "github.com/lewtec/lewkit/x/driver/battery/ios"
	_ "github.com/lewtec/lewkit/x/driver/battery/linux"
)
