package prelude

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lewtec/lewkit/x/test"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRunWritesFile(t *testing.T) {
	dir := t.TempDir()
	app := filepath.Join(dir, "cmd", "app")
	writeTree(t, dir, map[string]string{
		"go.mod":                  "module example.com/app\n\ngo 1.27\n",
		"cmd/app/root.go":         "package main\n",
		"cmd/app/foo/root.go":     "package foo\n",
		"cmd/app/foo/bar/root.go": "package bar\n",
		"cmd/app/skip/other.go":   "package skip\n",
		"cmd/app/main.go":         "package main\n",
	})
	dest := filepath.Join(app, "prelude.go")
	require.NoError(t, Run(t.Context(), app, dest))

	got := readFile(t, dest)
	assert.Contains(t, got, "Code generated by lewkit generate prelude. DO NOT EDIT.")
	assert.Contains(t, got, "package main")
	assert.Contains(t, got, `_ "example.com/app/cmd/app/foo"`)
	assert.Contains(t, got, `_ "example.com/app/cmd/app/foo/bar"`)
	assert.NotContains(t, got, "Registry")
	assert.NotContains(t, got, "GetCommand")
	assert.NotContains(t, got, "func init")
	assert.NotContains(t, got, "example.com/app/cmd/app\"")
	assert.NotContains(t, got, "skip")
	assert.Less(t, strings.Index(got, "/foo\""), strings.Index(got, "/foo/bar\""))
}

func TestRunStdout(t *testing.T) {
	dir := t.TempDir()
	app := filepath.Join(dir, "cmd", "app")
	writeTree(t, dir, map[string]string{
		"go.mod":              "module example.com/app\n\ngo 1.27\n",
		"cmd/app/foo/root.go": "package foo\n",
	})
	got := test.Stdout(t, func() {
		require.NoError(t, Run(t.Context(), app, ""))
	})
	assert.Contains(t, got, "package prelude")
	assert.Contains(t, got, `_ "example.com/app/cmd/app/foo"`)
	_, err := os.Stat(filepath.Join(app, "prelude.go"))
	assert.ErrorIs(t, err, os.ErrNotExist)
}

func TestRunNoRootGo(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, map[string]string{
		"go.mod":  "module example.com/app\n\ngo 1.27\n",
		"root.go": "package main\n",
	})
	got := test.Stdout(t, func() {
		require.NoError(t, Run(t.Context(), dir, ""))
	})
	assert.Contains(t, got, "package prelude")
	assert.NotContains(t, got, `_ "`)
}

func TestRunNoGoMod(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "root.go"), []byte("package main\n"), 0o644))
	err := Run(t.Context(), dir, "")
	assert.ErrorIs(t, err, errNoGoMod)
}

func TestRunEmptyDir(t *testing.T) {
	err := Run(t.Context(), "", "")
	assert.ErrorIs(t, err, errDirRequired)
}

func writeTree(t *testing.T, root string, files map[string]string) {
	t.Helper()
	for rel, body := range files {
		path := filepath.Join(root, rel)
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
		require.NoError(t, os.WriteFile(path, []byte(body), 0o644))
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	require.NoError(t, err)
	return string(b)
}
