package prelude

import (
	"strings"
	"testing"

	"github.com/lewtec/lewkit/x/path"
	"github.com/lewtec/lewkit/x/test"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRunWritesFile(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, map[string]string{
		"go.mod":                  "module example.com/app\n\ngo 1.27\n",
		"cmd/app/root.go":         "package main\n",
		"cmd/app/foo/root.go":     "package foo\n",
		"cmd/app/foo/bar/root.go": "package bar\n",
		"cmd/app/skip/other.go":   "package skip\n",
		"cmd/app/main.go":         "package main\n",
	})
	app := path.New(dir).Join("cmd", "app")
	dest := app.Join("prelude.go")
	require.NoError(t, Run(t.Context(), app.String(), dest.String()))

	root, err := path.Open(dir)
	require.NoError(t, err)
	test.CloseOnCleanup(t, root)
	got := readPath(t, root, path.New("cmd", "app", "prelude.go"))
	assert.Contains(t, got, "Code generated by lewkit generate prelude. DO NOT EDIT.")
	assert.Contains(t, got, "package main")
	assert.Contains(t, got, `_ "example.com/app/cmd/app/foo"`)
	assert.Contains(t, got, `_ "example.com/app/cmd/app/foo/bar"`)
	assert.NotContains(t, got, "Registry")
	assert.NotContains(t, got, "GetCommand")
	assert.NotContains(t, got, "func init")
	assert.NotContains(t, got, "example.com/app/cmd/app\"")
	assert.NotContains(t, got, "skip")
	assert.Less(t, strings.Index(got, `/foo"`), strings.Index(got, `/foo/bar"`))
}

func TestRunStdout(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, map[string]string{
		"go.mod":              "module example.com/app\n\ngo 1.27\n",
		"cmd/app/foo/root.go": "package foo\n",
	})
	app := path.New(dir).Join("cmd", "app")
	got := test.Stdout(t, func() {
		require.NoError(t, Run(t.Context(), app.String(), ""))
	})
	assert.Contains(t, got, "package prelude")
	assert.Contains(t, got, `_ "example.com/app/cmd/app/foo"`)
	root, err := path.Open(dir)
	require.NoError(t, err)
	test.CloseOnCleanup(t, root)
	ok, err := path.New("cmd", "app", "prelude.go").Exists(root)
	require.NoError(t, err)
	assert.False(t, ok)
}

func TestRunNoRootGo(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, map[string]string{
		"go.mod":  "module example.com/app\n\ngo 1.27\n",
		"root.go": "package main\n",
	})
	got := test.Stdout(t, func() {
		require.NoError(t, Run(t.Context(), dir, ""))
	})
	assert.Contains(t, got, "package prelude")
	assert.NotContains(t, got, `_ "`)
}

func TestRunNoGoMod(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, map[string]string{
		"root.go": "package main\n",
	})
	err := Run(t.Context(), dir, "")
	assert.ErrorIs(t, err, errNoGoMod)
}

func TestRunEmptyDir(t *testing.T) {
	err := Run(t.Context(), "", "")
	assert.ErrorIs(t, err, errDirRequired)
}

func writeTree(t *testing.T, root string, files map[string]string) {
	t.Helper()
	fsys, err := path.Open(root)
	require.NoError(t, err)
	test.CloseOnCleanup(t, fsys)
	for rel, body := range files {
		name := path.New(rel)
		if parent := name.Parent(); parent.String() != "." {
			require.NoError(t, parent.MkdirAll(fsys, 0o755))
		}
		require.NoError(t, name.WriteFile(fsys, []byte(body), 0o644))
	}
}

func readPath(t *testing.T, fsys *path.Root, name path.Path) string {
	t.Helper()
	body, err := name.ReadFile(fsys)
	require.NoError(t, err)
	return string(body)
}
