package prelude

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lewtec/lewkit/x/path"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRun(t *testing.T) {
	dir := t.TempDir()
	app := filepath.Join(dir, "cmd", "app")
	writeTree(t, dir, map[string]string{
		"go.mod":                  "module example.com/app\n\ngo 1.27\n",
		"cmd/app/root.go":         "package main\n",
		"cmd/app/foo/root.go":     "// comment\npackage foo\n",
		"cmd/app/foo/bar/root.go": "package bar\n",
		"cmd/app/skip/other.go":   "package skip\n",
		"cmd/app/initpkg/root.go": "package init\n",
	})

	require.NoError(t, Run(t.Context(), app))

	got := readFile(t, filepath.Join(app, "prelude.go"))
	assert.Contains(t, got, "Code generated by lewkit generate prelude. DO NOT EDIT.")
	assert.Contains(t, got, "package main")
	assert.Contains(t, got, `pkg_foo "example.com/app/cmd/app/foo"`)
	assert.Contains(t, got, `pkg_init "example.com/app/cmd/app/initpkg"`)
	assert.Contains(t, got, "Registry.FromGetter(pkg_foo.GetCommand)")
	assert.Contains(t, got, "Registry.FromGetter(pkg_init.GetCommand)")
	assert.NotContains(t, got, "skip")
	assert.Less(t, strings.Index(got, "pkg_foo"), strings.Index(got, "pkg_init"))

	nested := readFile(t, filepath.Join(app, "foo", "prelude.go"))
	assert.Contains(t, nested, "package foo")
	assert.Contains(t, nested, `pkg_bar "example.com/app/cmd/app/foo/bar"`)
	assert.Contains(t, nested, "Registry.FromGetter(pkg_bar.GetCommand)")

	_, err := os.Stat(filepath.Join(app, "skip", "prelude.go"))
	assert.ErrorIs(t, err, os.ErrNotExist)
	_, err = os.Stat(filepath.Join(app, "foo", "bar", "prelude.go"))
	assert.ErrorIs(t, err, os.ErrNotExist)
}

func TestRunRelativeDir(t *testing.T) {
	dir := t.TempDir()
	app := filepath.Join(dir, "cmd", "app")
	writeTree(t, dir, map[string]string{
		"go.mod":              "module example.com/app\n\ngo 1.27\n",
		"cmd/app/root.go":     "package main\n",
		"cmd/app/foo/root.go": "package foo\n",
	})
	t.Chdir(app)
	require.NoError(t, Run(t.Context(), "."))
	got := readFile(t, filepath.Join(app, "prelude.go"))
	assert.Contains(t, got, `pkg_foo "example.com/app/cmd/app/foo"`)
}

func TestRunNoChildren(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, map[string]string{
		"go.mod":  "module example.com/app\n\ngo 1.27\n",
		"root.go": "package main\n",
	})
	require.NoError(t, Run(t.Context(), dir))
	_, err := os.Stat(filepath.Join(dir, "prelude.go"))
	assert.ErrorIs(t, err, os.ErrNotExist)
}

func TestRunNoGoMod(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "root.go"), []byte("package main\n"), 0o644))
	err := Run(t.Context(), dir)
	assert.ErrorIs(t, err, errNoGoMod)
}

func TestRunEmptyDir(t *testing.T) {
	err := Run(t.Context(), "")
	assert.ErrorIs(t, err, errDirRequired)
}

func TestPackageOfFileSkipsComments(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "root.go"), []byte("// header\n\npackage demo\n"), 0o644))
	filesystem, err := path.Open(dir)
	require.NoError(t, err)
	t.Cleanup(func() { filesystem.Close() })
	packageName, err := packageOfFile(filesystem, path.New("root.go"))
	require.NoError(t, err)
	assert.Equal(t, "demo", packageName)
}

func writeTree(t *testing.T, root string, files map[string]string) {
	t.Helper()
	for rel, body := range files {
		path := filepath.Join(root, rel)
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
		require.NoError(t, os.WriteFile(path, []byte(body), 0o644))
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	require.NoError(t, err)
	return string(b)
}
