package prelude

import (
	"bytes"

	"github.com/dave/jennifer/jen"
	"github.com/lewtec/lewkit/x/path"
)

const generatedBy = "Code generated by lewkit generate prelude. DO NOT EDIT."

func write(filesystem *path.Root, current commandRoot, children []commandRoot) error {
	file := jen.NewFile(current.packageName)
	file.HeaderComment(generatedBy)
	for _, child := range children {
		file.ImportAlias(child.importPath, "pkg_"+child.packageName)
	}
	file.Func().Id("init").Params().BlockFunc(func(group *jen.Group) {
		for _, child := range children {
			group.Id("Registry").Dot("FromGetter").Call(jen.Qual(child.importPath, "GetCommand"))
		}
	})
	var body bytes.Buffer
	if err := file.Render(&body); err != nil {
		return err
	}
	return current.directory.Join("prelude.go").WriteFile(filesystem, body.Bytes(), 0o644)
}
