package prelude

import (
	"path/filepath"

	"github.com/dave/jennifer/jen"
)

const generatedBy = "Code generated by lewkit generate prelude. DO NOT EDIT."

func write(dir, pkg string, children []root) error {
	f := jen.NewFile(pkg)
	f.HeaderComment(generatedBy)
	for _, c := range children {
		f.ImportAlias(c.imp, "pkg_"+c.pkg)
	}
	f.Func().Id("init").Params().BlockFunc(func(g *jen.Group) {
		for _, c := range children {
			g.Id("Registry").Dot("FromGetter").Call(jen.Qual(c.imp, "GetCommand"))
		}
	})
	return f.Save(filepath.Join(dir, "prelude.go"))
}
