package prelude

import "github.com/dave/jennifer/jen"

const generatedBy = "Code generated by lewkit generate prelude. DO NOT EDIT."

func jenFile(packageName string, imports []string) *jen.File {
	file := jen.NewFile(packageName)
	file.HeaderComment(generatedBy)
	for _, imp := range imports {
		file.Anon(imp)
	}
	return file
}
