// Package prelude blank-imports every registration tree in this module.
// A directory with no Go file is skipped. Its children attach to the
// package above it. Regenerated by `go generate` at the module root.
package prelude
