// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/prelude"
	_ "github.com/lewtec/lewkit/x/http/asset/prelude"
	_ "github.com/lewtec/lewkit/x/tool/prelude"
)
