// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/tray/cocoa"
	_ "github.com/lewtec/lewkit/x/driver/tray/dbus"
	_ "github.com/lewtec/lewkit/x/driver/tray/win32"
)
