// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/terminal/alacritty"
	_ "github.com/lewtec/lewkit/x/driver/terminal/foot"
	_ "github.com/lewtec/lewkit/x/driver/terminal/kitty"
)
