// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/clipboard/pbcopy"
	_ "github.com/lewtec/lewkit/x/driver/clipboard/winclip"
	_ "github.com/lewtec/lewkit/x/driver/clipboard/wlcopy"
	_ "github.com/lewtec/lewkit/x/driver/clipboard/xclip"
)
