package generate

import (
	"path"
	"path/filepath"

	"github.com/dave/jennifer/jen"
)

const generatedBy = "Code generated by lewkit db. DO NOT EDIT."

func write(dir, pkg, imp string, engines []engine, methods []method, structs []structType) error {
	if err := writeFS(dir, pkg, engines); err != nil {
		return err
	}
	return writeQueries(dir, pkg, imp, engines, methods, structs)
}

func writeFS(dir, pkg string, engines []engine) error {
	f := jen.NewFile(pkg)
	f.HeaderComment(generatedBy)
	var dirs []string
	for _, e := range engines {
		dirs = append(dirs, e.dir)
	}
	f.Comment(joinEmbed(dirs))
	f.Var().Id("FS").Qual("embed", "FS")
	return f.Save(filepath.Join(dir, "zz_fs.go"))
}

func writeQueries(dir, pkg, imp string, engines []engine, methods []method, structs []structType) error {
	f := jen.NewFile(pkg)
	f.HeaderComment(generatedBy)
	for _, e := range engines {
		f.Anon(path.Join("github.com/lewtec/lewkit/x/db", e.dir))
	}

	need := map[string]bool{}
	for _, n := range localNames(methods) {
		need[n] = true
	}
	for _, st := range structs {
		if !need[st.name] {
			continue
		}
		var fields []jen.Code
		for _, fl := range st.fields {
			fields = append(fields, jen.Id(fl.name).Add(jenType(fl.typ)))
		}
		f.Type().Id(st.name).Struct(fields...)
	}

	var iface []jen.Code
	for _, m := range methods {
		iface = append(iface, jen.Id(m.name).Params(jenParams(m.params)...).Params(jenParams(m.results)...))
	}
	f.Type().Id("Queries").Interface(iface...)

	for _, e := range engines {
		writeWrap(f, imp, e, methods)
	}

	f.Func().Id("New").Params(jen.Id("url").String()).Func().Params(jen.Qual("github.com/lewtec/lewkit/x/db", "DBTX")).Id("Queries").Block(
		jen.Return(jen.Func().Params(jen.Id("tx").Qual("github.com/lewtec/lewkit/x/db", "DBTX")).Id("Queries").Block(
			jen.Switch(jen.Qual("github.com/lewtec/lewkit/x/db", "Scheme").Call(jen.Id("url"))).Block(newCases(imp, engines)...),
		)),
	)

	f.Func().Id("Open").Params(
		jen.Id("ctx").Qual("context", "Context"),
		jen.Id("a").Op("*").Qual("github.com/lewtec/lewkit/x/db", "Arg").Types(jen.Id("Queries")),
	).Error().Block(
		jen.Return(jen.Id("a").Dot("Open").Call(
			jen.Id("ctx"),
			jen.Id("FS"),
			jen.Id("New").Call(jen.Id("a").Dot("Value").Call().Dot("URL").Call()),
		)),
	)

	return f.Save(filepath.Join(dir, "zz_queries.go"))
}

func newCases(imp string, engines []engine) []jen.Code {
	var cases []jen.Code
	for _, e := range engines {
		wrap := wrapName(e.dir)
		engImp := path.Join(imp, e.dir)
		c := jen.Case(jen.Lit(e.dir)).Block(
			jen.Return(jen.Id(wrap).Values(jen.Dict{
				jen.Id("q"): jen.Qual(engImp, "New").Call(jen.Id("tx")),
			})),
		)
		cases = append(cases, c)
	}
	cases = append(cases, jen.Default().Block(jen.Return(jen.Nil())))
	return cases
}

func wrapName(dir string) string {
	return dir + "Wrap"
}

func writeWrap(f *jen.File, imp string, e engine, methods []method) {
	engImp := path.Join(imp, e.dir)
	wrap := wrapName(e.dir)
	f.Type().Id(wrap).Struct(jen.Id("q").Op("*").Qual(engImp, "Queries"))
	for _, m := range methods {
		writeWrapMethod(f, engImp, wrap, m)
	}
}

func writeWrapMethod(f *jen.File, engImp, wrap string, m method) {
	params := jenParams(m.params)
	results := jenParams(m.results)
	var args []jen.Code
	for _, p := range m.params {
		arg := jen.Id(p.name)
		if p.typ.local() {
			arg = jen.Qual(engImp, p.typ.baseName()).Call(jen.Id(p.name))
		}
		args = append(args, arg)
	}
	call := jen.Id("w").Dot("q").Dot(m.name).Call(args...)

	f.Func().Params(jen.Id("w").Id(wrap)).Id(m.name).Params(params...).Params(results...).Block(wrapBody(m, call)...)
}

func wrapBody(m method, call jen.Code) []jen.Code {
	var locals []field
	for _, r := range m.results {
		if r.typ.local() {
			locals = append(locals, r)
		}
	}
	if len(locals) == 0 {
		return []jen.Code{jen.Return(call)}
	}
	var lhs []jen.Code
	for i, r := range m.results {
		if r.name != "" {
			lhs = append(lhs, jen.Id(r.name))
			continue
		}
		lhs = append(lhs, jen.Id(tmpName(i, r.typ)))
	}
	body := []jen.Code{jen.List(lhs...).Op(":=").Add(call)}
	var rets []jen.Code
	for i, r := range m.results {
		id := r.name
		if id == "" {
			id = tmpName(i, r.typ)
		}
		if r.typ.kind == "slice" && r.typ.local() {
			item := r.typ.baseName()
			body = append(body,
				jen.Id("out").Op(":=").Make(jen.Index().Id(item), jen.Len(jen.Id(id))),
				jen.For(jen.Id("i").Op(":=").Range().Id(id)).Block(
					jen.Id("out").Index(jen.Id("i")).Op("=").Id(item).Call(jen.Id(id).Index(jen.Id("i"))),
				),
			)
			rets = append(rets, jen.Id("out"))
			continue
		}
		if r.typ.local() {
			rets = append(rets, jen.Id(r.typ.baseName()).Call(jen.Id(id)))
			continue
		}
		rets = append(rets, jen.Id(id))
	}
	body = append(body, jen.Return(rets...))
	return body
}

func tmpName(i int, t typeExpr) string {
	if t.kind == "ident" && t.name == "error" {
		return "err"
	}
	if t.local() {
		return "v"
	}
	return "r"
}

func jenParams(fs []field) []jen.Code {
	var out []jen.Code
	for _, fl := range fs {
		if fl.name == "" {
			out = append(out, jenType(fl.typ))
			continue
		}
		out = append(out, jen.Id(fl.name).Add(jenType(fl.typ)))
	}
	return out
}

func jenType(t typeExpr) *jen.Statement {
	switch t.kind {
	case "ident":
		return jen.Id(t.name)
	case "qual":
		return jen.Qual(qualPath(t.pkg), t.name)
	case "pointer":
		return jen.Op("*").Add(jenType(*t.elem))
	case "slice":
		return jen.Index().Add(jenType(*t.elem))
	case "ellipsis":
		return jen.Op("...").Add(jenType(*t.elem))
	case "any":
		return jen.Any()
	default:
		return jen.Any()
	}
}

func qualPath(pkg string) string {
	switch pkg {
	case "context":
		return "context"
	case "sql":
		return "database/sql"
	case "time":
		return "time"
	default:
		return pkg
	}
}

func joinEmbed(dirs []string) string {
	n := len("//go:embed")
	for _, d := range dirs {
		n += 1 + len(d)
	}
	b := make([]byte, 0, n)
	b = append(b, "//go:embed"...)
	for _, d := range dirs {
		b = append(b, ' ')
		b = append(b, d...)
	}
	return string(b)
}
