// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/chooser/cocoa"
	_ "github.com/lewtec/lewkit/x/driver/chooser/gtk"
	_ "github.com/lewtec/lewkit/x/driver/chooser/qt"
	_ "github.com/lewtec/lewkit/x/driver/chooser/win32"
)
