// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/messagebox/android"
	_ "github.com/lewtec/lewkit/x/driver/messagebox/cocoa"
	_ "github.com/lewtec/lewkit/x/driver/messagebox/gtk"
	_ "github.com/lewtec/lewkit/x/driver/messagebox/host"
	_ "github.com/lewtec/lewkit/x/driver/messagebox/win32"
	_ "github.com/lewtec/lewkit/x/driver/messagebox/zenity"
)
