// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/http/asset/htmx"
	_ "github.com/lewtec/lewkit/x/http/asset/jquery"
	_ "github.com/lewtec/lewkit/x/http/asset/lewtec_logo"
	_ "github.com/lewtec/lewkit/x/http/asset/sakuracss"
	_ "github.com/lewtec/lewkit/x/http/asset/tailwindcss"
)
