// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/lewkit/x/driver/daynight/cocoa"
	_ "github.com/lewtec/lewkit/x/driver/daynight/fixed"
	_ "github.com/lewtec/lewkit/x/driver/daynight/portal"
	_ "github.com/lewtec/lewkit/x/driver/daynight/win32"
)
